# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
min_time = 0
