theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = [ "jump_view_left" ]
C-l = [ "jump_view_right" ]
C-k = [ "jump_view_up" ]
C-j = [ "jump_view_down" ]

[editor.cursor-shape]
insert = "bar"
