eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/Applications/WezTerm.app/Contents/MacOS:$PATH"
export PATH="$PATH:$(go env GOPATH)/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.bun/bin"
